# Generated by Django 5.2.11 on 2026-02-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_recipe_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedRecipeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Original URL as submitted', max_length=2048)),
                ('normalized_url', models.CharField(db_index=True, max_length=2048, unique=True)),
                ('result', models.JSONField(help_text='Normalized import result: name, metadata, ingredients, steps, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parsed recipe cache',
                'verbose_name_plural': 'Parsed recipe cache',
                'ordering': ['-created_at'],
            },
        ),
    ]
