# Generated by Django 5.2.11 on 2026-02-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_parsed_recipe_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingsession',
            name='step_durations_seconds',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
