# Generated by Django 5.2.11 on 2026-02-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_add_owner_to_cookingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingsession',
            name='step_durations_seconds',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
