# Generated by Django 5.2.11 on 2026-02-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_allow_null_step_durations_seconds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CookingSession',
            new_name='Meal',
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-started_at'], 'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
    ]
