# Generated by Django 5.2.11 on 2026-02-06 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_cookingsession_to_meal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeversion',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If False, only owner can see this version.'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipe_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='recipes.recipeversion'),
        ),
    ]
