# Generated by Django 5.2.11 on 2026-02-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipeversion_owner_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeversion',
            name='main_picture',
            field=models.URLField(blank=True, help_text='URL of the main recipe image.', max_length=2048),
        ),
    ]
